"""Strategy classification flags + audited results merged into the dashboard catalog.

strategy_flags.yaml (hand-maintained) holds the filter flags; strategy_audit.json
is generated by ``python -m tools.strategy_audit.report`` from real backtests.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

_DIR = Path(__file__).resolve().parent
FLAGS_PATH = _DIR / "strategy_flags.yaml"
AUDIT_PATH = _DIR / "strategy_audit.json"
FLAG_GROUPS = ["horizon", "segment", "instrument", "direction", "bias", "hedging", "style"]
STATUS_BY_VERDICT = {"KEEP": "active", "WATCH": "experimental", "EXPERIMENTAL": "experimental",
                     "DEPRECATE": "deprecated"}


def load_flags() -> dict[str, dict[str, Any]]:
    if not FLAGS_PATH.exists():
        return {}
    return yaml.safe_load(FLAGS_PATH.read_text(encoding="utf-8")) or {}


def load_audit() -> dict[str, Any]:
    if not AUDIT_PATH.exists():
        return {}
    return json.loads(AUDIT_PATH.read_text(encoding="utf-8"))


def _stats(a: dict[str, Any]) -> dict[str, str]:
    if "trades" not in a:
        label = "Pending audit" if a.get("verdict") == "PENDING" else "Not backtestable"
        return {"return_pct": label, "win_rate": "-", "max_dd": "-", "sharpe": "-"}
    pf = a.get("profit_factor")
    return {
        "return_pct": f"{a['return_pct'] * 100:+.1f}% net",
        "win_rate": f"{a['win_rate'] * 100:.1f}%",
        "max_dd": f"{a['max_dd_pct'] * 100:.1f}%",
        "sharpe": f"PF {pf:.2f}" if pf is not None else "PF inf",
    }


def enrich_catalog(catalog: dict[str, dict[str, Any]]) -> None:
    """Attach flags / status / audit to every catalog entry in place."""
    flags, audit = load_flags(), load_audit()
    audited = audit.get("strategies", {})
    for sid, entry in catalog.items():
        f = flags.get(sid, {})
        entry["flags"] = {g: list(f.get(g, [])) for g in FLAG_GROUPS}
        a = audited.get(sid)
        status = f.get("status_override") or (STATUS_BY_VERDICT.get(a["verdict"], "experimental") if a else "experimental")
        entry["status"] = status
        entry["status_reason"] = f.get("status_reason") or (a or {}).get("why", "not audited yet")
        if a:
            entry["audit"] = {**a, "generated": audit.get("generated")}
            entry["historical_stats"] = _stats(a)
